version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    expose:
      - "3000"
    environment:
      - VIRTUAL_HOST=localhost
      - VIRTUAL_PORT=3000
      - WDS_SOCKET_PORT=0
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 5

  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    expose:
      - "3000"
    environment:
      - VIRTUAL_HOST=localhost
      - VIRTUAL_PORT=3000
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  nginx-proxy:
    image: jwilder/nginx-proxy:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs:ro
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    environment:
      - DEFAULT_HOST=localhost
      - HTTPS_METHOD=redirect
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  html:
  vhost:

networks:
  app_network:
    driver: bridge